# Generated by Django 5.2.12 on 2026-03-31 18:52

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0016_sha256_checksums"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="latest_content",
            field=models.TextField(
                blank=True,
                help_text="Materialized effective content for root documents. Uses the latest version content when available.",
                null=True,
                verbose_name="latest content",
            ),
        ),
    ]
